/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.App;
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.curso.service.CursoService;
import java.awt.Color;
import javax.swing.*;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Taila
 */

public class CursoListar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());

    private CursoService cursoService;
    
    /**
     * Creates new form CursoListar
     */
    public CursoListar() {
        initComponents();
        configurarCores();
        
        try {
        cursoService = App.ctx.getBean(CursoService.class); // pega o bean Spring

        // Se o banco estiver vazio, adiciona cursos de exemplo
        if (cursoService.findAll().isEmpty()) {
            for (Curso c : gerarCursosExemplo()) {
                cursoService.save(c);
            }
        }

        // Atualiza a tabela com todos os cursos
        carregarTabela(cursoService.findAll());

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Erro ao inicializar serviço: " + e.getMessage());
        e.printStackTrace();
    
    }

}
    
    

    private void configurarCores() {
    // Configura a cor de fundo da janela e da tabela
    Color azulEscuroTeal = new Color(30, 63, 95); 
    this.getContentPane().setBackground(azulEscuroTeal); 
    jScrollPane1.getViewport().setBackground(azulEscuroTeal);
    jTabela.setForeground(Color.BLACK);
    jTabela.setGridColor(new Color(40, 80, 120));
    }

     // Método para gerar cursos de exemplo caso o banco esteja vazio
    private void carregarExemplosNaTabela() {
    List<Curso> exemplos = gerarCursosExemplo();
    carregarTabela(exemplos);
}

    public List<Curso> gerarCursosExemplo() {
    List<Curso> cursos = new ArrayList<>();

    Curso c1 = new Curso();
    c1.setNome("Informática Básica");
    c1.setCodigoCurso("CUR001");
    c1.setCargaHoraria(40);
    c1.setAtivo(true);
    cursos.add(c1);

    Curso c2 = new Curso();
    c2.setNome("Administração");
    c2.setCodigoCurso("CUR002");
    c2.setCargaHoraria(60);
    c2.setAtivo(true);
    cursos.add(c2);

    Curso c3 = new Curso();
    c3.setNome("Enfermagem");
    c3.setCodigoCurso("CUR003");
    c3.setCargaHoraria(80);
    c3.setAtivo(true);
    cursos.add(c3);

    Curso c4 = new Curso();
    c4.setNome("Programação Java");
    c4.setCodigoCurso("CUR004");
    c4.setCargaHoraria(100);
    c4.setAtivo(true);
    cursos.add(c4);

    Curso c5 = new Curso();
    c5.setNome("Manutenção de Computadores");
    c5.setCodigoCurso("CUR005");
    c5.setCargaHoraria(50);
    c5.setAtivo(true);
    cursos.add(c5);

    return cursos;
}



    private void carregarTabela(java.util.List<Curso> cursos) {
     
    ImageIcon iconTrash = new ImageIcon(getClass().getResource("/images/trash.png"));
    ImageIcon iconEdit = new ImageIcon(getClass().getResource("/images/edit.png"));

    DefaultTableModel model = (DefaultTableModel) jTabela.getModel();
    model.setRowCount(0);// Limpa a tabela

    // Adiciona cada curso como uma linha da tabela
    
    if (cursos != null) {
        for (Curso c : cursos) {
            model.addRow(new Object[]{
                c.getNome(),
                c.getCodigoCurso(),
                c.getCargaHoraria(),
                c.isAtivo(),
                iconTrash,
                iconEdit
            });
        }
    }
    
    // Ajusta a largura das colunas
        jTabela.getColumnModel().getColumn(0).setPreferredWidth(150);  // Código
        jTabela.getColumnModel().getColumn(1).setPreferredWidth(100); // Nome
        jTabela.getColumnModel().getColumn(2).setPreferredWidth(100);  // Carga Horária
        jTabela.getColumnModel().getColumn(3).setPreferredWidth(50);  // Ativo
}
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        txtPesquisar = new java.awt.TextField();
        jbCadastrar = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Curso", "CódCurso", "Cargahorária", "Ativo", "Remover", "Editar"
            }
        ) {
            Class[] types = new Class [] {
                String.class,   // Curso
                String.class,   // Código
                Integer.class,  // Carga
                Boolean.class,  // Ativo
                ImageIcon.class, // Remover
                ImageIcon.class  // Editar
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabela);
        if (jTabela.getColumnModel().getColumnCount() > 0) {
            jTabela.getColumnModel().getColumn(0).setHeaderValue("Curso");
            jTabela.getColumnModel().getColumn(1).setHeaderValue("CódCurso");
            jTabela.getColumnModel().getColumn(2).setHeaderValue("Cargahorária");
            jTabela.getColumnModel().getColumn(3).setHeaderValue("Ativo");
            jTabela.getColumnModel().getColumn(4).setHeaderValue("Remover");
            jTabela.getColumnModel().getColumn(5).setHeaderValue("Editar");
        }

        txtPesquisar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPesquisar.setText("Pesquisar...");
        txtPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisarMouseClicked(evt);
            }
        });
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });

        jbCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jbCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPesquisar)
                .addGap(35, 35, 35)
                .addComponent(jbCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbCadastrar)
                            .addComponent(jbPesquisar))))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void jTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseClicked
        int linha = jTabela.getSelectedRow();
        int coluna = jTabela.getSelectedColumn();
        if (linha < 0) return;

        String nomeCurso = jTabela.getValueAt(linha, 0).toString();
        List<Curso> cursosEncontrados = cursoService.findByNome(nomeCurso);

        if (cursosEncontrados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum curso encontrado com o nome: " + nomeCurso);
            return;
        }

        Curso cursoSelecionado = cursosEncontrados.get(0);

        if (coluna == 4) { // Remover
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja remover o curso?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                cursoService.delete(cursoSelecionado);
                JOptionPane.showMessageDialog(this, "Curso removido com sucesso!");
                carregarTabela(cursoService.findAll());
            }
        }

        if (coluna == 5) { // Editar
            CursoEditar tela = new CursoEditar(cursoSelecionado, this.cursoService);
            tela.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jTabelaMouseClicked

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        CursoSave tela = new CursoSave();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void txtPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarMouseClicked
        txtPesquisar.setText("");
        carregarTabela(cursoService.findAll());
    }//GEN-LAST:event_txtPesquisarMouseClicked

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
       try {
            String texto = txtPesquisar.getText();
            List<Curso> resultado;

            if (texto == null || texto.trim().isEmpty() || texto.equals("Pesquisar...")) {
                resultado = cursoService.findAll();
            } else {
                resultado = cursoService.findByNome(texto.trim());
            }

            carregarTabela(resultado);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar: " + e.getMessage());
            logger.severe("Erro no botão pesquisar: " + e.getMessage());
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbPesquisar;
    private java.awt.TextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
