/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.entity.Curso;
import br.com.ifba.curso.dao.CursoDao;
import java.awt.Color;
import javax.swing.JOptionPane;
import br.com.ifba.curso.service.CursoIService;

/**
 *
 * @author Taila
 */
public class CursoEditar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoEditar.class.getName());

    private CursoIService cursoService;
    private CursoListar telaListar;
    private Curso curso;
    /**
     * Creates new form CursoSave
     */
    public CursoEditar(Curso cursoSelecionado, CursoIService service) {
        initComponents();
        setLocationRelativeTo(null);

        this.curso = cursoSelecionado;
        this.cursoService = service;

        configurarCores();
        carregarCurso(cursoSelecionado);
    }

    /** Configuração de cores */
    private void configurarCores() {
        Color azulEscuroTeal = new Color(30, 63, 95);
        this.getContentPane().setBackground(azulEscuroTeal);

        jCurso.setForeground(Color.WHITE);
        jCodigo.setForeground(Color.WHITE);
        jHorario.setForeground(Color.WHITE);
        jtitulo.setForeground(Color.WHITE);
        jCheckBoxAtivo.setForeground(Color.WHITE);
    }

    /** Preenche os campos com o curso selecionado */
    public void carregarCurso(Curso cursoSelecionado) {
        txtCurso.setText(cursoSelecionado.getNome());
        txtCodigo.setText(cursoSelecionado.getCodigoCurso());
        txtCarga.setText(String.valueOf(cursoSelecionado.getCargaHoraria()));
        jCheckBoxAtivo.setSelected(cursoSelecionado.isAtivo());
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtitulo = new javax.swing.JLabel();
        jCurso = new javax.swing.JLabel();
        jCodigo = new javax.swing.JLabel();
        jHorario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCurso = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCarga = new javax.swing.JTextPane();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jCheckBoxAtivo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jtitulo.setText("Editar Curso");

        jCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCurso.setText("Nome do Curso:");

        jCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCodigo.setText("Código do Curso:");

        jHorario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jHorario.setText("Carga Horária:");

        jScrollPane1.setViewportView(txtCurso);

        jScrollPane2.setViewportView(txtCodigo);

        jScrollPane3.setViewportView(txtCarga);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jCheckBoxAtivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxAtivo.setText("Ativo");
        jCheckBoxAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAtivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jHorario)
                            .addComponent(jCurso)
                            .addComponent(jCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(86, 86, 86)
                        .addComponent(btnCancelar)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBoxAtivo)
                        .addGap(164, 164, 164))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jtitulo)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCodigo)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jHorario)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxAtivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
        if (curso == null) {
            JOptionPane.showMessageDialog(this, "Erro interno: objeto Curso está nulo!");
            return;
        }

        String nome = txtCurso.getText().trim();
        String carga = txtCarga.getText().trim();
        boolean ativo = jCheckBoxAtivo.isSelected();

        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o nome do curso.");
            return;
        }

        if (carga.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a carga horária.");
            return;
        }

        curso.setNome(nome);
        curso.setCargaHoraria(Integer.parseInt(carga));
        curso.setAtivo(ativo);

        cursoService.update(curso);

        JOptionPane.showMessageDialog(this, "Curso atualizado com sucesso!");

        CursoListar tela = new CursoListar();
        tela.setVisible(true);
        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao atualizar curso: " + e.getMessage());
        logger.severe("Erro ao atualizar: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
        new CursoListar().setVisible(true);
        // Apenas volta sem salvar alterações
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jCheckBoxAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAtivoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox jCheckBoxAtivo;
    private javax.swing.JLabel jCodigo;
    private javax.swing.JLabel jCurso;
    private javax.swing.JLabel jHorario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jtitulo;
    private javax.swing.JTextPane txtCarga;
    private javax.swing.JTextPane txtCodigo;
    private javax.swing.JTextPane txtCurso;
    // End of variables declaration//GEN-END:variables
}
