/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.App;
import br.com.ifba.curso.entity.Curso;
import java.awt.Color;
import javax.swing.JOptionPane;
import br.com.ifba.curso.service.CursoService;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;



/**
 *
 * @author Taila
 */

public class CursoSave extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoSave.class.getName());

    private CursoService cursoService;
    
    /**
     * Creates new form CursoCadastrar
     */
    public CursoSave() {
        initComponents();
        setLocationRelativeTo(null);
        this.cursoService = App.ctx.getBean(CursoService.class);


        
        // Define fundo estilizado da tela
        Color azulEscuroTeal = new Color(30, 63, 95); 
        this.getContentPane().setBackground(azulEscuroTeal);
        // Deixa os textos brancos para contraste com fundo escuro
        jlCurso.setForeground(Color.WHITE);
        jLabel1.setForeground(Color.WHITE);
        jlCarga.setForeground(Color.WHITE);
        jCheckBoxAtivo.setForeground(Color.WHITE);
        jLabel2.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCurso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtCurso = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcodigoCurso = new javax.swing.JTextPane();
        jCheckBoxAtivo = new javax.swing.JCheckBox();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jlCarga = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCarga = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlCurso.setText("Nome:");

        jScrollPane1.setViewportView(jtxtCurso);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Código do curso:");

        jScrollPane2.setViewportView(txtcodigoCurso);

        jCheckBoxAtivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxAtivo.setText("Ativo");
        jCheckBoxAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAtivoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Cadastrar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jlCarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlCarga.setText("Carga horária:");

        jScrollPane3.setViewportView(txtCarga);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Cadastrar Curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlCarga)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jlCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxAtivo)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnSalvar)
                        .addGap(32, 32, 32)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCarga))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxAtivo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAtivoActionPerformed
        
    }//GEN-LAST:event_jCheckBoxAtivoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       try{
            String nome = jtxtCurso.getText().trim();
            String codigo = txtcodigoCurso.getText().trim();
            String cargaH = txtCarga.getText().trim();
            boolean ativo = jCheckBoxAtivo.isSelected();
            // Lê os valores informados pelo usuário
            
            if(nome.isEmpty() || codigo.isEmpty() || cargaH.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
                // Impede salvar curso com campos faltando
            }
            
            int cargaHoraria;
        try {
            cargaHoraria = Integer.parseInt(cargaH); // <-- AQUI
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Carga horária deve ser um número inteiro!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
            // Cria o objeto e preenche com os dados do formulário
            Curso curso = new Curso();
            curso.setNome(nome);
            curso.setCodigoCurso(codigo);
            curso.setCargaHoraria(cargaHoraria);
            curso.setAtivo(ativo);
            
            // Salva no banco de dados
            cursoService.save(curso);
            
            // Fecha tela e volta para listagem
            new CursoListar().setVisible(true);
            this.dispose();
               
            JOptionPane.showMessageDialog(this, "Curso cadastrado com sucesso!");
            logger.info("Curso cadastrado: " + nome);
            
            // Limpa campos após salvar
            jtxtCurso.setText("");
            txtcodigoCurso.setText("");
            txtCarga.setText("");
            jCheckBoxAtivo.setSelected(false);
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar curso: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            logger.severe("Erro ao cadastrar curso: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
        new CursoListar().setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed
    private void limparCampos() {
        jtxtCurso.setText("");
        txtcodigoCurso.setText("");
        txtCarga.setText("");
        jCheckBoxAtivo.setSelected(false);
    }
    
    
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox jCheckBoxAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlCarga;
    private javax.swing.JLabel jlCurso;
    private javax.swing.JTextPane jtxtCurso;
    private javax.swing.JTextPane txtCarga;
    private javax.swing.JTextPane txtcodigoCurso;
    // End of variables declaration//GEN-END:variables
    

}
